### ISSUE TITLE
[Optional] Auto-generate Textures for Meteors and Catalysts

### ISSUE THREAD

**Issue by dipo33** [dipo33/Meteors#6]
### Description
To enhance visual representation, investigate and implement automatic texture generation for meteors and catalysts.

### Tasks
- [ ] Research the NEI feature for exporting item/block textures to `.png`.
- [ ] Implement a similar algorithm to auto-generate and export textures for meteors and catalysts.
- [ ] Save the generated textures to the server for use in the application.

### Acceptance Criteria
- Textures for new meteors and catalysts are automatically generated and saved to the server.
